Repository InternationalScratchWiki/ScratchWikiSkin2, pull requests merged in 2018-09, with the labels that each got.

#39 Translate new 2 strings for mobile
  i18n/ja.json
Labels: i18n, mobile, prgtm

#38 Mobile design!
  ScratchWikiSkin.skin.php
  ScratchWikiSkinTemplate.php
  i18n/en.json
  i18n/ja.json
  i18n/qqq.json
  resources/main.css
Labels: design, enhancement, mobile, prnr

#41 Hotfix mobile design
  CREDITS
  ScratchWikiSkinTemplate.php
  i18n/en.json
  i18n/ja.json
  i18n/qqq.json
  resources/Hamburger_icon.svg
  resources/User.svg
  resources/main.css
Labels: design, mobile, prio-high, prnr
