Repository InternationalScratchWiki/ScratchWikiSkin2, pull requests merged in 2020-09, with the labels that each got.

#63 Translated to Hungarian!
  i18n/hu.json
Labels: i18n, prgtm

#66 removed fancy z-index values for header and sidebar and added border-box to navigation so it is exactly 50px tall (closes #65)
  resources/main.css
Labels: design, prgtm

#67 Support JavaScript-disabled clients
  ScratchWikiSkinTemplate.php
Labels: prio-low, prnr
