Repository InternationalScratchWiki/ScratchWikiSkin2, pull requests merged in 2021-01, with the labels that each got.

#74 Add a SkinScratchWikiSkin::initPage
  ScratchWikiSkin.skin.php
Labels: prgtm

#77 Fix edit pencil image
  ScratchWikiSkinTemplate.php
  resources/css/main.css
Labels: mobile, prgtm, prio-low

#79 Restrict skin header preference to when skin is selected
  ScratchWikiSkin.skin.php
Labels: enhancement, prnr

#78 Use wgLogos['wordmark'] for sourcing stratchwiki logo
  ScratchWikiSkinTemplate.php
  resources/css/main.css
Labels: enhancement, prio-low, prnr
