Repository InternationalScratchWiki/ScratchWikiSkin2, pull requests merged in 2022-10, with the labels that each got.

#110 Remove User::getOption
  ScratchWikiSkin.skin.php
Labels: prio-medium

#118 add padding to linkless tabs
  ScratchWikiSkinTemplate.php
  resources/css/main.css
Labels: enhancement

#119 Fix outdated donation link
  ScratchWikiSkinTemplate.php
Labels: bug, prnr, prio-high
